import { Listing, Reservation, EventInquiry, ApprovalMode, ReservationStatus, EventInquiryStatus } from '../types';

// This file now only serves as the initial "seed" data for our simulated API.
// All data manipulation logic is handled in `services/api.ts`.

export const initialListings: Listing[] = [
  {
    id: 'l1',
    hostId: 'h1',
    address: '1 Dr Carlton B Goodlett Pl, San Francisco, CA',
    description: 'Secure garage spot, perfect for sedans. 24/7 access.',
    rate: 5,
    rateType: 'hourly',
    availability: { start: '00:00', end: '23:59' },
    approvalMode: ApprovalMode.AUTOMATIC,
    location: { latitude: 37.779, longitude: -122.419 },
    suitableForEvents: false,
  },
  {
    id: 'l2',
    hostId: 'h1',
    address: '345 California St, San Francisco, CA',
    description: 'Private driveway, available on weekends. Also suitable for small outdoor gatherings or pop-ups.',
    rate: 25,
    rateType: 'flat',
    availability: { start: '09:00', end: '18:00' },
    approvalMode: ApprovalMode.MANUAL,
    location: { latitude: 37.794, longitude: -122.400 },
    suitableForEvents: true,
  },
  {
    id: 'l3',
    hostId: 'h2',
    address: '555 Howard St, San Francisco, CA',
    description: 'Compact car spot in a quiet neighborhood. Close to downtown.',
    rate: 3,
    rateType: 'hourly',
    availability: { start: '08:00', end: '20:00' },
    approvalMode: ApprovalMode.AUTOMATIC,
    location: { latitude: 37.785, longitude: -122.396 },
    suitableForEvents: false,
  },
  {
    id: 'l4',
    hostId: 'h1',
    address: '501 Stanyan St, San Francisco, CA',
    description: 'Spacious spot near Golden Gate Park. Ideal for day trips or small photo shoots.',
    rate: 7,
    rateType: 'hourly',
    availability: { start: '06:00', end: '22:00' },
    approvalMode: ApprovalMode.MANUAL,
    location: { latitude: 37.771, longitude: -122.453 },
    suitableForEvents: true,
  },
  {
    id: 'l5',
    hostId: 'h2',
    address: '2800 Leavenworth St, San Francisco, CA',
    description: 'Covered parking at Fisherman\'s Wharf. Great for tourists.',
    rate: 40,
    rateType: 'flat',
    availability: { start: '10:00', end: '21:00' },
    approvalMode: ApprovalMode.AUTOMATIC,
    location: { latitude: 37.807, longitude: -122.417 },
    suitableForEvents: false,
  },
  {
    id: 'l6',
    hostId: 'h1',
    address: '3220 20th St, San Francisco, CA',
    description: 'Easy access spot in the vibrant Mission District. Can be used for food truck parking or small markets.',
    rate: 4,
    rateType: 'hourly',
    availability: { start: '00:00', end: '23:59' },
    approvalMode: ApprovalMode.AUTOMATIC,
    location: { latitude: 37.758, longitude: -122.412 },
    suitableForEvents: true,
  },
  {
    id: 'l7',
    hostId: 'h3',
    address: '747 Howard St, San Francisco, CA',
    description: 'Secure underground parking in SoMa, near Moscone Center.',
    rate: 30,
    rateType: 'flat',
    availability: { start: '07:00', end: '23:00' },
    approvalMode: ApprovalMode.MANUAL,
    location: { latitude: 37.783, longitude: -122.403 },
    suitableForEvents: false,
  },
];

export const initialReservations: Reservation[] = [
    {
        id: 'r1',
        listingId: 'l2',
        driverId: 'd1',
        startTime: new Date(new Date().setDate(new Date().getDate() + 1)),
        endTime: new Date(new Date(new Date().setDate(new Date().getDate() + 1)).setHours(17)),
        status: ReservationStatus.PENDING,
    },
    {
        id: 'r2',
        listingId: 'l1',
        driverId: 'd2',
        startTime: new Date(),
        endTime: new Date(new Date().setHours(new Date().getHours() + 2)),
        status: ReservationStatus.APPROVED,
    },
    {
        id: 'r3',
        listingId: 'l4',
        driverId: 'd3',
        startTime: new Date(new Date().setDate(new Date().getDate() + 2)),
        endTime: new Date(new Date(new Date().setDate(new Date().getDate() + 2)).setHours(15)),
        status: ReservationStatus.PENDING,
    }
];

export const initialEventInquiries: EventInquiry[] = [
    {
        id: 'ei1',
        listingId: 'l2',
        hostId: 'h1',
        userName: 'Alice Johnson',
        userEmail: 'alice@example.com',
        eventType: 'Birthday Party',
        eventDate: new Date(new Date().setDate(new Date().getDate() + 30)),
        numberOfAttendees: 25,
        message: 'Looking for a small, private outdoor space for a birthday celebration. Please let me know if this is possible.',
        status: EventInquiryStatus.PENDING,
    },
    {
        id: 'ei2',
        listingId: 'l4',
        hostId: 'h1',
        userName: 'Bob Williams',
        userEmail: 'bob@example.com',
        eventType: 'Photo Shoot',
        eventDate: new Date(new Date().setDate(new Date().getDate() + 14)),
        numberOfAttendees: 5,
        message: 'We are a small crew looking to do a fashion photo shoot. The proximity to the park is ideal. We would need the space for about 4 hours.',
        status: EventInquiryStatus.CONTACTED,
    }
];
